CREATE TABLE MEMBER(
ID BIGINT AUTO_INCREMENT not null,
NAME VARCHAR(50) not null,
FAMILY_ID BIGINT not null,
CREATION_TIME TIMESTAMP not null,
MOD_USER VARCHAR(50) not null,
MOD_TIME TIMESTAMP not null
);