CREATE TABLE MEMBER(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) not null,
FAMILY_ID BIGINT not null ,
CREATION_TIME TIMESTAMP not null,
MOD_USER VARCHAR(50) not null,
MOD_TIME TIMESTAMP not null
);

ALTER TABLE MEMBER
ADD FOREIGN KEY (FAMILY_ID) 
REFERENCES FAMILY(ID);

ALTER TABLE MEMBER
ADD CONSTRAINT UNIQUE_MEMBER_NAME
UNIQUE(NAME);