CREATE TABLE MEAL(
ID BIGINT AUTO_INCREMENT not null,
NAME VARCHAR(50) not null,
DESCRIPTION VARCHAR(500),
FAMILY_ID BIGINT not null,
CREATION_TIME TIMESTAMP not null,
MOD_USER VARCHAR(5) not null,
MOD_TIME TIMESTAMP not null
);