CREATE TABLE MEAL(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) not null,
DESCRIPTION VARCHAR(500),
FAMILY_ID BIGINT not null,
CREATION_TIME TIMESTAMP not null,
MOD_USER VARCHAR(5) not null,
MOD_TIME TIMESTAMP not null
);

ALTER TABLE MEAL
ADD FOREIGN KEY (FAMILY_ID) 
REFERENCES FAMILY(ID);

ALTER TABLE MEAL
ADD CONSTRAINT UNIQUE_MEAL_NAME
UNIQUE(NAME);